### ISSUE TITLE
Warp workflow doesn't work on shape files

### ISSUE THREAD

**Issue by tsalo** [PennLINC/xcp_d_test_data#1]
```
230714-21:29:35,480 nipype.workflow INFO:
	 ***********************************
230714-21:29:35,482 nipype.workflow ERROR:
	 could not run node: warp_thickness_to_template_wf.lh_apply_transforms_wf.resample_to_fsLR32k
230714-21:29:35,482 nipype.workflow INFO:
	 crashfile: /tmp/crash-20230714-212918-root-resample_to_fsLR32k-b57ce4aa-a73b-4b54-8ad0-be588c9a6f16.pklz
230714-21:29:35,482 nipype.workflow ERROR:
	 could not run node: warp_thickness_to_template_wf.rh_apply_transforms_wf.resample_to_fsLR32k
230714-21:29:35,482 nipype.workflow INFO:
	 crashfile: /tmp/crash-20230714-212922-root-resample_to_fsLR32k-65ad1324-5814-4ce2-9a48-560d5fe57570.pklz
230714-21:29:35,482 nipype.workflow INFO:
	 ***********************************
Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/linear.py", line 47, in run
    node.run(updatehash=updatehash)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1380, in _run_interface
    result = self._collate_results(
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 1293, in _collate_results
    raise NodeExecutionError(
nipype.pipeline.engine.nodes.NodeExecutionError: Subnodes of node: resample_to_fsLR32k failed:
Subnode 1 failed
Error: Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
    setattr(outputs, key, val)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
    self.error(objekt, name, str(value))
  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
    raise TraitError(
traits.trait_errors.TraitError: The 'out_file' trait of a _CiftiSurfaceResampleOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/Users/taylor/Documents/linc/xcp_d_test_data/data/work/dcan/warp_thickness_to_template_wf/lh_apply_transforms_wf/resample_to_fsLR32k/mapflow/_resample_to_fsLR32k1/resampled_sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii' <class 'str'> was specified.

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 400, in run
    outputs = self.aggregate_outputs(runtime)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
    raise FileNotFoundError(msg)
FileNotFoundError: No such file or directory '/Users/taylor/Documents/linc/xcp_d_test_data/data/work/dcan/warp_thickness_to_template_wf/lh_apply_transforms_wf/resample_to_fsLR32k/mapflow/_resample_to_fsLR32k1/resampled_sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii' for output 'out_file' of a CiftiSurfaceResample interface

Traceback (most recent call last):

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/utils.py", line 94, in nodelist_runner
    result = node.run(updatehash=updatehash)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 527, in run
    result = self._run_interface(execute=True)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 645, in _run_interface
    return self._run_command(execute)

  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/nodes.py", line 771, in _run_command
    raise NodeExecutionError(msg)

nipype.pipeline.engine.nodes.NodeExecutionError: Exception raised while executing Node _resample_to_fsLR32k1.

Cmdline:
	wb_command  -surface-resample /Users/taylor/Documents/linc/xcp_d_test_data/data/fmriprep-reduced/sub-1648798153/ses-PNC1/anat/sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii   /Users/taylor/Documents/linc/xcp_d_test_data/data/work/dcan/warp_thickness_to_template_wf/lh_apply_transforms_wf/surface_sphere_project_unproject/lh.sphere.reg_converted_deformed.surf.gii  /home/xcp_d/.cache/templateflow/tpl-fsLR/tpl-fsLR_hemi-L_den-32k_sphere.surf.gii   BARYCENTRIC   resampled_sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii
Stdout:

Stderr:

	While running:
	wb_command -surface-resample /Users/taylor/Documents/linc/xcp_d_test_data/data/fmriprep-reduced/sub-1648798153/ses-PNC1/anat/sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii /Users/taylor/Documents/linc/xcp_d_test_data/data/work/dcan/warp_thickness_to_template_wf/lh_apply_transforms_wf/surface_sphere_project_unproject/lh.sphere.reg_converted_deformed.surf.gii /home/xcp_d/.cache/templateflow/tpl-fsLR/tpl-fsLR_hemi-L_den-32k_sphere.surf.gii BARYCENTRIC resampled_sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii

	ERROR: NAME OF FILE: sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii
	PATH TO FILE: /Users/taylor/Documents/linc/xcp_d_test_data/data/fmriprep-reduced/sub-1648798153/ses-PNC1/anat

	Number of data arrays MUST be two in a SurfaceFile.

Traceback:
	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 453, in aggregate_outputs
	    setattr(outputs, key, val)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 330, in validate
	    value = super(File, self).validate(objekt, name, value, return_pathlike=True)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/traits_extension.py", line 135, in validate
	    self.error(objekt, name, str(value))
	  File "/usr/local/miniconda/lib/python3.8/site-packages/traits/base_trait_handler.py", line 74, in error
	    raise TraitError(
	traits.trait_errors.TraitError: The 'out_file' trait of a _CiftiSurfaceResampleOutputSpec instance must be a pathlike object or string representing an existing file, but a value of '/Users/taylor/Documents/linc/xcp_d_test_data/data/work/dcan/warp_thickness_to_template_wf/lh_apply_transforms_wf/resample_to_fsLR32k/mapflow/_resample_to_fsLR32k1/resampled_sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii' <class 'str'> was specified.

	During handling of the above exception, another exception occurred:

	Traceback (most recent call last):
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 400, in run
	    outputs = self.aggregate_outputs(runtime)
	  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/interfaces/base/core.py", line 460, in aggregate_outputs
	    raise FileNotFoundError(msg)
	FileNotFoundError: No such file or directory '/Users/taylor/Documents/linc/xcp_d_test_data/data/work/dcan/warp_thickness_to_template_wf/lh_apply_transforms_wf/resample_to_fsLR32k/mapflow/_resample_to_fsLR32k1/resampled_sub-1648798153_ses-PNC1_acq-refaced_hemi-L_thickness.shape.gii' for output 'out_file' of a CiftiSurfaceResample interface



The above exception was the direct cause of the following exception:

Traceback (most recent call last):
  File "/Users/taylor/Documents/linc/xcp_d_test_data/modify_for_dcan.py", line 182, in <module>
    main(fmri_dir, out_dir, work_dir)
  File "/Users/taylor/Documents/linc/xcp_d_test_data/modify_for_dcan.py", line 134, in main
    wf_res = wf.run()
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/engine/workflows.py", line 638, in run
    runner.run(execgraph, updatehash=updatehash, config=self.config)
  File "/usr/local/miniconda/lib/python3.8/site-packages/nipype/pipeline/plugins/linear.py", line 82, in run
    raise error from cause
RuntimeError: 2 raised. Re-raising first.
```

**Comment by tsalo** [comment]
I ended up splitting up the CIFTIs instead.
